using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Homework04._12;
namespace Homework04._12
{
    internal class Exercise8_10
    {
        public static void RunCountries()
        {
            Dictionary<string, string> capitals = new Dictionary<string, string>()
           {
              { "Afghanistan", "Kabul" },
    { "Albania", "Tirana" },
    { "Algeria", "Algiers" },
    { "Andorra", "Andorra la Vella" },
    { "Angola", "Luanda" },
    { "Antigua and Barbuda", "Saint John's" },
    { "Argentina", "Buenos Aires" },
    { "Armenia", "Yerevan" },
    { "Australia", "Canberra" },
    { "Austria", "Vienna" },
    { "Azerbaijan", "Baku" },
    { "Bahamas", "Nassau" },
    { "Bahrain", "Manama" },
    { "Bangladesh", "Dhaka" },
    { "Barbados", "Bridgetown" },
    { "Belarus", "Minsk" },
    { "Belgium", "Brussels" },
    { "Belize", "Belmopan" },
    { "Benin", "Porto-Novo" },
    { "Bhutan", "Thimphu" },
    { "Bolivia", "Sucre" },
    { "Bosnia and Herzegovina", "Sarajevo" },
    { "Botswana", "Gaborone" },
    { "Brazil", "Brasília" },
    { "Brunei", "Bandar Seri Begawan" },
    { "Bulgaria", "Sofia" },
    { "Burkina Faso", "Ouagadougou" },
    { "Burundi", "Gitega" },
    { "Cabo Verde", "Praia" },
    { "Cambodia", "Phnom Penh" },
    { "Cameroon", "Yaoundé" },
    { "Canada", "Ottawa" },
    { "Central African Republic", "Bangui" },
    { "Chad", "N'Djamena" },
    { "Chile", "Santiago" },
    { "China", "Beijing" },
    { "Colombia", "Bogotá" },
    { "Comoros", "Moroni" },
    { "Congo, Democratic Republic of the", "Kinshasa" },
    { "Congo, Republic of the", "Brazzaville" },
    { "Costa Rica", "San José" },
    { "Croatia", "Zagreb" },
    { "Cuba", "Havana" },
    { "Cyprus", "Nicosia" },
    { "Czech Republic", "Prague" },
    { "Denmark", "Copenhagen" },
    { "Djibouti", "Djibouti" },
    { "Dominica", "Roseau" },
    { "Dominican Republic", "Santo Domingo" },
    { "Ecuador", "Quito" },
    { "Egypt", "Cairo" },
    { "El Salvador", "San Salvador" },
    { "Equatorial Guinea", "Malabo" },
    { "Eritrea", "Asmara" },
    { "Estonia", "Tallinn" },
    { "Eswatini", "Mbabane" },
    { "Ethiopia", "Addis Ababa" },
    { "Fiji", "Suva" },
    { "Finland", "Helsinki" },
    { "France", "Paris" },
    { "Gabon", "Libreville" },
    { "Gambia", "Banjul" },
    { "Georgia", "Tbilisi" },
    { "Germany", "Berlin" },
    { "Ghana", "Accra" },
    { "Greece", "Athens" },
    { "Grenada", "Saint George's" },
    { "Guatemala", "Guatemala City" },
    { "Guinea", "Conakry" },
    { "Guinea-Bissau", "Bissau" },
    { "Guyana", "Georgetown" },
    { "Haiti", "Port-au-Prince" },
    { "Honduras", "Tegucigalpa" },
    { "Hungary", "Budapest" },
    { "Iceland", "Reykjavik" },
    { "India", "New Delhi" },
    { "Indonesia", "Jakarta" },
    { "Iran", "Tehran" },
    { "Iraq", "Baghdad" },
    { "Ireland", "Dublin" },
    { "Israel", "Jerusalem" },
    { "Italy", "Rome" },
    { "Jamaica", "Kingston" },
    { "Japan", "Tokyo" },
    { "Jordan", "Amman" },
    { "Kazakhstan", "Astana" },
    { "Kenya", "Nairobi" },
    { "Kiribati", "Tarawa" },
    { "Kuwait", "Kuwait City" },
    { "Kyrgyzstan", "Bishkek" },
    { "Laos", "Vientiane" },
    { "Latvia", "Riga" },
    { "Lebanon", "Beirut" },
    { "Lesotho", "Maseru" },
    { "Liberia", "Monrovia" },
    { "Libya", "Tripoli" },
    { "Liechtenstein", "Vaduz" },
    { "Lithuania", "Vilnius" },
    { "Luxembourg", "Luxembourg" },
    { "Madagascar", "Antananarivo" },
    { "Malawi", "Lilongwe" },
    { "Malaysia", "Kuala Lumpur" },
    { "Maldives", "Malé" },
    { "Mali", "Bamako" },
    { "Malta", "Valletta" },
    { "Marshall Islands", "Majuro" },
    { "Mauritania", "Nouakchott" },
    { "Mauritius", "Port Louis" },
    { "Mexico", "Mexico City" },
    { "Micronesia", "Palikir" },
    { "Moldova", "Chișinău" },
    { "Monaco", "Monaco" },
    { "Mongolia", "Ulaanbaatar" },
    { "Montenegro", "Podgorica" },
    { "Morocco", "Rabat" },
    { "Mozambique", "Maputo" },
    { "Myanmar", "Naypyidaw" },
    { "Namibia", "Windhoek" },
    { "Nauru", "Yaren" },
    { "Nepal", "Kathmandu" },
    { "Netherlands", "Amsterdam" },
    { "New Zealand", "Wellington" },
    { "Nicaragua", "Managua" },
    { "Niger", "Niamey" },
    { "Nigeria", "Abuja" },
    { "North Korea", "Pyongyang" },
    { "North Macedonia", "Skopje" },
    { "Norway", "Oslo" },
    { "Oman", "Muscat" },
    { "Pakistan", "Islamabad" },
    { "Palau", "Ngerulmud" },
    { "Panama", "Panama City" },
    { "Papua New Guinea", "Port Moresby" },
    { "Paraguay", "Asunción" },
    { "Peru", "Lima" },
    { "Philippines", "Manila" },
    { "Poland", "Warsaw" },
    { "Portugal", "Lisbon" },
    { "Qatar", "Doha" },
    { "Romania", "Bucharest" },
    { "Russia", "Moscow" },
    { "Rwanda", "Kigali" },
    { "Saint Kitts and Nevis", "Basseterre" },
    { "Saint Lucia", "Castries" },
    { "Saint Vincent and the Grenadines", "Kingstown" },
    { "Samoa", "Apia" },
    { "San Marino", "San Marino" },
    { "Sao Tome and Principe", "São Tomé" },
    { "Saudi Arabia", "Riyadh" },
    { "Senegal", "Dakar" },
    { "Serbia", "Belgrade" },
    { "Seychelles", "Victoria" },
    { "Sierra Leone", "Freetown" },
    { "Singapore", "Singapore" },
    { "Slovakia", "Bratislava" },
    { "Slovenia", "Ljubljana" },
    { "Solomon Islands", "Honiara" },
    { "Somalia", "Mogadishu" },
    { "South Africa", "Pretoria" },
    { "South Korea", "Seoul" },
    { "South Sudan", "Juba" },
    { "Spain", "Madrid" },
    { "Sri Lanka", "Sri Jayawardenepura Kotte" },
    { "Sudan", "Khartoum" },
    { "Suriname", "Paramaribo" },
    { "Sweden", "Stockholm" },
    { "Switzerland", "Bern" },
    { "Syria", "Damascus" },
    { "Taiwan", "Taipei" },
    { "Tajikistan", "Dushanbe" },
    { "Tanzania", "Dodoma" },
    { "Thailand", "Bangkok" },
    { "Timor-Leste", "Dili" },
    { "Togo", "Lomé" },
    { "Tonga", "Nukuʻalofa" },
    { "Trinidad and Tobago", "Port of Spain" },
    { "Tunisia", "Tunis" },
    { "Turkey", "Ankara" },
    { "Turkmenistan", "Ashgabat" },
    { "Tuvalu", "Funafuti" },
    { "Uganda", "Kampala" },
    { "Ukraine", "Kyiv" },
    { "United Arab Emirates", "Abu Dhabi" },
    { "United Kingdom", "London" },
    { "United States", "Washington, D.C." },
    { "Uruguay", "Montevideo" },
    { "Uzbekistan", "Tashkent" },
    { "Vanuatu", "Port Vila" },
    { "Vatican City", "Vatican City" },
    { "Venezuela", "Caracas" },
    { "Vietnam", "Hanoi" },
    { "Yemen", "Sana'a" },
    { "Zambia", "Lusaka" },
    { "Zimbabwe", "Harare" }
           };

            while (true)
            {
                Console.WriteLine("Enter a country to find its capital or type 'exit' to see all countries and their capitals:");
                string country = Console.ReadLine();

                if (country.ToLower() == "exit")
                    break;

                if (capitals.TryGetValue(country, out string capital))
                {
                    Console.WriteLine($"The capital of {country} is: {capital}");
                }
                else
                {
                    Console.WriteLine($"Sorry, {country} is not in the list.");
                }

            }

            Console.WriteLine("All countries and their capitals:");
            foreach (var pair in capitals)
            {
                Console.WriteLine($"Country: {pair.Key} -> Capital: {pair.Value}");
            }
        }
    }
}

